server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: api-gateway


zuul:
  routes:
    #用户服务
    user-center-service: /apigateway/user-center/**
    #核心基础服务
    core-service: /apigateway/core-service/**
    #权限服务
    authority-service: /apigateway/authority-service/**
  ignored-patterns: /*-service/**
  sensitive-headers:

